# Generated by Django 3.2.14 on 2022-07-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=200)),
                ('compAddress1', models.CharField(max_length=200)),
                ('compAddress2', models.CharField(max_length=200)),
                ('compCity', models.CharField(max_length=100)),
                ('compState', models.CharField(max_length=100)),
                ('compCountry', models.CharField(max_length=100)),
                ('compTelephone', models.CharField(max_length=100)),
                ('compFax', models.CharField(max_length=100)),
                ('compEmail', models.CharField(max_length=100)),
                ('compLogo', models.CharField(max_length=100)),
                ('compCurrency', models.CharField(max_length=3)),
            ],
        ),
    ]
