# Generated by Django 3.2.14 on 2022-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='compZipcode',
            field=models.CharField(default=606001, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='compLogo',
            field=models.ImageField(upload_to=''),
        ),
    ]
