# Generated by Django 3.2.14 on 2022-07-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0002_auto_20220727_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='compCode',
            field=models.CharField(default='TACTB', max_length=50),
            preserve_default=False,
        ),
    ]
