# Generated by Django 3.2.14 on 2022-07-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0003_companyinfo_compcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finYear', models.IntegerField()),
                ('dateFrom1', models.DateField()),
                ('dateTo1', models.DateField()),
                ('dateFrom2', models.DateField()),
                ('dateTo2', models.DateField()),
                ('dateFrom3', models.DateField()),
                ('dateTo3', models.DateField()),
                ('dateFrom4', models.DateField()),
                ('dateTo5', models.DateField()),
                ('dateFrom6', models.DateField()),
                ('dateTo6', models.DateField()),
                ('dateFrom7', models.DateField()),
                ('dateTo7', models.DateField()),
                ('dateFrom8', models.DateField()),
                ('dateTo8', models.DateField()),
                ('dateFrom9', models.DateField()),
                ('dateTo9', models.DateField()),
                ('dateFrom10', models.DateField()),
                ('dateTo10', models.DateField()),
                ('dateFrom11', models.DateField()),
                ('dateTo11', models.DateField()),
                ('dateFrom12', models.DateField()),
                ('dateTo12', models.DateField()),
                ('compCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo')),
            ],
        ),
    ]
