# Generated by Django 3.2.14 on 2022-07-30 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tactb', '0006_auto_20220727_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccess', models.TextField()),
                ('accesibleCompany', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesibleModules', models.TextField()),
                ('compCode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountCode', models.CharField(max_length=50)),
                ('accountNmae', models.CharField(max_length=200)),
                ('accountType', models.CharField(max_length=20)),
                ('compCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo')),
            ],
        ),
    ]
