# Generated by Django 3.2.14 on 2022-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0007_companycoa_modaccess_usermodaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycoa',
            name='accountNmae',
        ),
        migrations.AddField(
            model_name='companycoa',
            name='accountName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
