# Generated by Django 3.2.14 on 2022-08-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0008_auto_20220803_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyCode', models.CharField(max_length=200)),
                ('partyName', models.CharField(max_length=200)),
                ('partyAddress1', models.CharField(max_length=200)),
                ('partyAddress2', models.CharField(max_length=200)),
                ('partyCity', models.CharField(max_length=100)),
                ('partyState', models.CharField(max_length=100)),
                ('partyCountry', models.CharField(max_length=100)),
                ('partyZipcode', models.CharField(max_length=100)),
                ('partyTelephone', models.CharField(max_length=100)),
                ('partyFax', models.CharField(max_length=100)),
                ('partyEmail', models.CharField(max_length=100)),
                ('compCode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo')),
            ],
        ),
    ]
