# Generated by Django 3.2.14 on 2022-08-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0010_partyinfo_partyname2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranType', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=200)),
                ('autonum', models.IntegerField()),
                ('compCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo')),
            ],
        ),
    ]
