# Generated by Django 3.2.14 on 2022-08-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0011_autonum'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranType', models.CharField(max_length=50)),
                ('accountCode', models.CharField(max_length=50)),
                ('compCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo')),
            ],
        ),
    ]
