# Generated by Django 3.2.14 on 2022-08-28 23:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0013_gldetail_glheader_glsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gldetail',
            name='date_trans',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 23, 26, 13, 805938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='glheader',
            name='date_trans',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 23, 26, 13, 805938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='glheader',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 23, 26, 13, 805938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='glsummary',
            name='document_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 23, 26, 13, 805938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='glsummary',
            name='enterd_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 23, 26, 13, 805938, tzinfo=utc)),
        ),
    ]
