# Generated by Django 3.2.14 on 2022-08-28 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0015_auto_20220829_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gldetail',
            name='line_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='gldetail',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='glheader',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='glsummary',
            name='reference_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='glsummary',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
