# Generated by Django 3.2.14 on 2022-08-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0016_auto_20220829_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gldetail',
            old_name='base_curr_amount',
            new_name='amount_forex',
        ),
        migrations.RenameField(
            model_name='gldetail',
            old_name='trx_curr_amount',
            new_name='amount_local',
        ),
    ]
