# Generated by Django 3.2.14 on 2022-08-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0017_auto_20220829_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='gldetail',
            name='compCode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo'),
        ),
        migrations.AddField(
            model_name='glheader',
            name='compCode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo'),
        ),
        migrations.AddField(
            model_name='glsummary',
            name='compCode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo'),
        ),
    ]
