# Generated by Django 3.2.14 on 2022-12-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0018_auto_20220829_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsId', models.CharField(max_length=200)),
                ('subsName', models.CharField(max_length=200)),
                ('subPosition', models.CharField(max_length=200)),
                ('subsPirivu', models.CharField(max_length=200)),
                ('subKottam', models.CharField(max_length=200)),
                ('subBranch', models.CharField(max_length=100)),
                ('subsNumber', models.CharField(max_length=100)),
                ('subsMobile', models.CharField(default='', max_length=100)),
                ('compCode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tactb.companyinfo')),
            ],
        ),
    ]
