# Generated by Django 3.2.14 on 2023-01-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0019_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='subKottam',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='subPosition',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='subsMobile',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='subsNumber',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='subsPirivu',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subAddr1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subAddr2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subDOB',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subDOR',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subPPOno',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='subBranch',
            field=models.CharField(default='', max_length=200),
        ),
    ]
