# Generated by Django 3.2.14 on 2023-01-29 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tactb', '0020_auto_20230101_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='subDOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='subDOR',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
